### ISSUE TITLE
Stereo mics cause infinite loop in get_config()

### ISSUE THREAD

**Issue by SonicZentropy** [kawaki-san/ds-transcriber#4]
Took me a bit to track down, but if your mic is stereo-only, config.rs's get_config() has a `while config.channels() != 1` infinite loop

**Comment by rtkay123** [comment]
Hey, apologies, I just saw this when I was cleaning up the crate. 
I don't have access to a stereo mic, but may you please check if 9d139f909995d04cde1681e2e09f05baa61dfec0 addresses it?
